# Generated by Django 5.1.7 on 2025-04-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('orsa_file', models.FileField(blank=True, null=True, upload_to='orsa_setups/')),
            ],
            options={
                'verbose_name_plural': 'BudgetSetup',
            },
        ),
        migrations.CreateModel(
            name='CashflowVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiums', models.CharField(blank=True, max_length=255, null=True)),
                ('claims', models.CharField(blank=True, max_length=255, null=True)),
                ('admin', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisitions', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('Insurance', 'Insurance'), ('Reinsurance', 'Insurance')], default='Insurance', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ifrs9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='ifrs9_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ifrs9',
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('input_parameters', models.TextField()),
                ('Run_Nr', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2024)),
                ('PrevRun_Nr', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2024)),
                ('NBRun_Nr', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='model_results/')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ModelRun',
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='calculations.modelrun')),
            ],
            options={
                'verbose_name_plural': 'RunLog',
            },
        ),
    ]
