# Generated by Django 5.1.7 on 2025-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_cashflowvariables_type_alter_modelrun_nbrun_nr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('income', 'Statement of Income'), ('position', 'Statement of Financial Position'), ('equity', 'Statement of Changes in Equity'), ('cashflows', 'Statement of Cashflows')], max_length=50)),
                ('file', models.FileField(upload_to='financials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
