# Generated by Django 5.1.7 on 2025-04-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0008_financialstatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
    ]
